const mockBuildingData = [
    {
      _id: '1',
      name: 'Edificio A',
      floors: [
        { _id: '1-1', name: 'Planta Baja' },
        { _id: '1-2', name: 'Primer Piso' },
        { _id: '1-3', name: 'Segundo Piso' },
      ],
    },
    {
      _id: '2',
      name: 'Edificio B',
      floors: [
        { _id: '2-1', name: 'Planta Baja' },
        { _id: '2-2', name: 'Primer Piso' },
        { _id: '2-3', name: 'Segundo Piso' },
        { _id: '2-4', name: 'Tercer Piso' },
      ],
    },
    {
      _id: '3',
      name: 'Edificio C',
      floors: [
        { _id: '3-1', name: 'Planta Baja' },
        { _id: '3-2', name: 'Primer Piso' },
      ],
    },
  ];
  
  const mockONTData = [
    {
      serial: 'MKPGb4e1aa3d',
      timestamp: '2023-07-11T21:00:00.000Z',
      wans: [
        {
          index: 'WAN1',
          connectionStatus: 'Connected',
          externalIPAddress: '192.168.1.100',
          name: 'Internet',
          natEnabled: true,
          addressingType: 'DHCP',
          bytesReceived: 10000000,
          bytesSent: 5000000,
          uptime: 86400,
          connectedWLANs: ['WLAN1', 'WLAN2'],
        },
        {
          index: 'WAN2',
          connectionStatus: 'Disconnected',
          externalIPAddress: '',
          name: 'VOIP',
          natEnabled: true,
          addressingType: 'Static',
          bytesReceived: 2000000,
          bytesSent: 1000000,
          uptime: 0,
          connectedWLANs: [],
        },
      ],
      wifi: [
        {
          interfaceIndex: 'WLAN1',
          ssid: 'Home Network',
          enable: true,
          status: 'Connected',
          channel: 6,
          totalAssociations: 10,
          totalBytesReceived: 50000000,
          totalBytesSent: 20000000,
        },
        {
          interfaceIndex: 'WLAN2',
          ssid: 'Guest Network',
          enable: true,
          status: 'Connected',
          channel: 11,
          totalAssociations: 5,
          totalBytesReceived: 10000000,
          totalBytesSent: 5000000,
        },
      ],
      hosts: [
        {
          hostIndex: 'HOST1',
          active: true,
          addressSource: 'DHCP',
          clientID: 'client1',
          hostName: 'laptop-1',
          iPAddress: '192.168.1.101',
          interfaceType: 'Ethernet',
          wlanId: 'WLAN1',
          leaseTimeRemaining: 3600,
          macAddress: '00:11:22:33:44:55',
          userClassID: 'user-class-1',
          vendorClassID: 'vendor-class-1',
        },
        {
          hostIndex: 'HOST2',
          active: true,
          addressSource: 'DHCP',
          clientID: 'client2',
          hostName: 'smartphone-1',
          iPAddress: '192.168.1.102',
          interfaceType: 'Wireless',
          wlanId: 'WLAN2',
          leaseTimeRemaining: 1800,
          macAddress: '66:77:88:99:AA:BB',
          userClassID: 'user-class-2',
          vendorClassID: 'vendor-class-2',
        },
      ],
      deviceInfo: {
        softwareVersion: 'v1.2.3',
      },
      gpon: {
        biasCurrent: 30,
        rxPower: -5,
        status: 'Normal',
        txPower: 5,
        transceiverTemperature: 35,
      },
      floor: '2nd Floor',
      building: 'Main Office',
    },
    {
      serial: 'STGUe0e66ee0',
      timestamp: '2023-07-11T21:00:00.000Z',
      wans: [
        {
          index: 'WAN1',
          connectionStatus: 'Connected',
          externalIPAddress: '192.168.3.22',
          name: 'Internet',
          natEnabled: true,
          addressingType: 'Static',
          bytesReceived: 128091341,
          bytesSent: 124391559,
          uptime: 86400,
          connectedWLANs: ['WLAN9'],
        },
        {
          index: 'WAN2',
          connectionStatus: 'Disconnected',
          externalIPAddress: '192.168.3.27',
          name: 'TV',
          natEnabled: false,
          addressingType: 'DHCP',
          bytesReceived: 20704718,
          bytesSent: 39122063,
          uptime: 0,
          connectedWLANs: ['WLAN8', 'WLAN7'],
        },
      ],
      wifi: [
        {
          interfaceIndex: 'WLAN1',
          ssid: 'ONT4W0',
          enable: true,
          status: 'Down',
          channel: 11,
          totalAssociations: 2,
          totalBytesReceived: 136734,
          totalBytesSent: 664052,
        },
        {
          interfaceIndex: 'WLAN2',
          ssid: 'ONT4W7_5G',
          enable: true,
          status: 'Up',
          channel: 11,
          totalAssociations: 6,
          totalBytesReceived: 10922669,
          totalBytesSent: 10298494,
        },
      ],
      hosts: [
        {
          hostIndex: 'HOST1',
          active: false,
          addressSource: 'DHCP',
          clientID: 'client3',
          hostName: 'desktop-1',
          iPAddress: '192.168.3.50',
          interfaceType: 'Ethernet',
          wlanId: null,
          leaseTimeRemaining: 0,
          macAddress: 'AA:BB:CC:DD:EE:FF',
          userClassID: 'user-class-3',
          vendorClassID: 'vendor-class-3',
        },
        {
          hostIndex: 'HOST2',
          active: true,
          addressSource: 'DHCP',
          clientID: 'client4',
          hostName: 'tablet-1',
          iPAddress: '192.168.3.51',
          interfaceType: 'Wireless',
          wlanId: 'WLAN8',
          leaseTimeRemaining: 2400,
          macAddress: '00:11:22:33:44:55',
          userClassID: 'user-class-4',
          vendorClassID: 'vendor-class-4',
        },
      ],
      deviceInfo: {
        softwareVersion: 'E10.V1.1.270',
      },
      gpon: {
        biasCurrent: 7,
        rxPower: -3,
        status: 'Up',
        txPower: 4,
        transceiverTemperature: 41,
      },
      floor: '1st Floor',
      building: 'Office Building',
    },
    {
      serial: 'STGUe0e57a18',
      timestamp: '2023-07-11T21:00:00.000Z',
      wans: [
        {
          index: 'WAN1',
          connectionStatus: 'Disconnected',
          externalIPAddress: '',
          name: 'EKCAST',
          natEnabled: false,
          addressingType: 'Static',
          bytesReceived: 34795766,
          bytesSent: 175371,
          uptime: 0,
          connectedWLANs: [],
        },
        {
          index: 'WAN2',
          connectionStatus: 'Connected',
          externalIPAddress: '',
          name: 'VOIP',
          natEnabled: true,
          addressingType: 'DHCP',
          bytesReceived: 181818985,
          bytesSent: 118328731,
          uptime: 86400,
          connectedWLANs: ['WLAN1', 'WLAN9'],
        },
        {
          index: 'WAN3',
          connectionStatus: 'Connected',
          externalIPAddress: '',
          name: 'TV',
          natEnabled: true,
          addressingType: 'Static',
          bytesReceived: 138644135,
          bytesSent: 165103238,
          uptime: 86400,
          connectedWLANs: ['WLAN2'],
        },
      ],
      wifi: [
        {
          interfaceIndex: 'WLAN1',
          ssid: 'ONT4W6_5G',
          enable: true,
          status: 'Up',
          channel: 44,
          totalAssociations: 8,
          totalBytesReceived: 11725699,
          totalBytesSent: 11781409,
        },
        {
          interfaceIndex: 'WLAN2',
          ssid: 'ONT4W1_5G',
          enable: true,
          status: 'Up',
          channel: 44,
          totalAssociations: 2,
          totalBytesReceived: 12023056,
          totalBytesSent: 12320484,
        },
      ],
      hosts: [
        {
          hostIndex: 'HOST1',
          active: true,
          addressSource: 'DHCP',
          clientID: 'client5',
          hostName: 'laptop-2',
          iPAddress: '192.168.0.100',
          interfaceType: 'Wireless',
          wlanId: 'WLAN1',
          leaseTimeRemaining: 3600,
          macAddress: '00:66:55:44:33:22',
          userClassID: 'user-class-5',
          vendorClassID: 'vendor-class-5',
        },
        {
          hostIndex: 'HOST2',
          active: false,
          addressSource: 'DHCP',
          clientID: 'client6',
          hostName: 'desktop-2',
          iPAddress: '192.168.0.101',
          interfaceType: 'Ethernet',
          wlanId: null,
          leaseTimeRemaining: 0,
          macAddress: 'FF:EE:DD:CC:BB:AA',
          userClassID: 'user-class-6',
          vendorClassID: 'vendor-class-6',
        },
      ],
      deviceInfo: {
        softwareVersion: 'E10.V1.1.270',
      },
      gpon: {
        biasCurrent: 8,
        rxPower: -11,
        status: 'Up',
        txPower: 3,
        transceiverTemperature: 10,
      },
      floor: '3rd Floor',
      building: 'Annex Building',
    },
  ];
  
  const mockTimeSeriesData = [
    {
      timestamp: '2023-06-01T00:00:00.000Z',
      totalBytesReceived: 1000000,
      totalBytesSent: 500000,
      totalWifiBytesReceived: 200000,
      totalWifiBytesSent: 100000,
      totalWifiAssociations: 50,
      activeWANs: 2,
      activeWiFiInterfaces: 3,
      connectedHosts: 10,
      failedConnections: 2,
    },
    {
      timestamp: '2023-06-02T00:00:00.000Z',
      totalBytesReceived: 1050000,
      totalBytesSent: 550000,
      totalWifiBytesReceived: 220000,
      totalWifiBytesSent: 120000,
      totalWifiAssociations: 55,
      activeWANs: 2,
      activeWiFiInterfaces: 3,
      connectedHosts: 12,
      failedConnections: 3,
    },
    {
      timestamp: '2023-06-03T00:00:00.000Z',
      totalBytesReceived: 1100000,
      totalBytesSent: 600000,
      totalWifiBytesReceived: 240000,
      totalWifiBytesSent: 140000,
      totalWifiAssociations: 60,
      activeWANs: 2,
      activeWiFiInterfaces: 3,
      connectedHosts: 15,
      failedConnections: 1,
    },
    // Más datos de series de tiempo...
  ];
  
  const mockConfig = {
    enabled: true,
    interval: 300,
  };
  
  export { mockBuildingData, mockONTData, mockTimeSeriesData, mockConfig };